stages:
  - .pre
  - build
  - unit-test
  - e2e-test
  - lint
  - audit
  - build-images
  - scan-images
  - push-images

image: node:16.15-bullseye-slim

variables:
  REGISTRY: $CI_REGISTRY
  REGISTRY_USER: $CI_REGISTRY_USER
  REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  REGISTRY_PROJECT: "/${CI_PROJECT_PATH}/"
  DOCKER_IMAGE: "docker:20.10-git"
  DOCKER_SERVICE: "docker:20.10-dind"
  DOCKER_TLS_CERTDIR: ""
  CYPRESS_IMAGE: "cypress/browsers:node16.14.2-slim-chrome100-ff99-edge"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

include:
  - local: .gitlab-ci/*.gitlab-ci.yml

#var-is-undefined-check:
#  stage: .pre
#  variables:
#    VAR: $CI_PIPELINE_SOURCE
#  script:
#    - echo $VAR
#  rules:
#    - if: $VAR == null
#
#var-is-not-undefined-check:
#  stage: .pre
#  variables:
#    VAR: $CI_PIPELINE_SOURCE
#  script:
#    - echo $VAR
#  rules:
#    - if: $VAR != null
#
#var-is-empty-check:
#  stage: .pre
#  variables:
#    VAR: $CI_PIPELINE_SOURCE
#  script:
#    - echo $VAR
#  rules:
#    - if: $VAR == ""
#
#var-is-not-empty-check:
#  stage: .pre
#  variables:
#    VAR: $CI_PIPELINE_SOURCE
#  script:
#    - echo $VAR
#  rules:
#    - if: $VAR != ""
#
#var1-equals-var2-check:
#  stage: .pre
#  variables:
#    VAR1: $CI_PIPELINE_SOURCE
#    VAR2: "external_pull_request_event"
#  script:
#    - echo $VAR1 == $VAR2
#  rules:
#    - if: $VAR1 == $VAR2
#
#var1-equals-not-var2-check:
#  stage: .pre
#  variables:
#    VAR1: $CI_PIPELINE_SOURCE
#    VAR2: "external_pull_request_event"
#  script:
#    - echo $VAR1 != $VAR2
#  rules:
#    - if: $VAR1 != $VAR2

check-config:
  stage: .pre
  interruptible: true
  allow_failure: true
  script:
    - echo $CI_DEFAULT_BRANCH
    - echo $CI_COMMIT_BRANCH
    - echo $CI_COMMIT_TAG
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_EXTERNAL_PULL_REQUEST_IID
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
    - echo $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA
    - echo $CI_MERGE_REQUEST_IID
    - echo $CI_MERGE_REQUEST_LABELS
    - echo $CI_MERGE_REQUEST_EVENT_TYPE
    - echo $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - echo $CI_COMMIT_BEFORE_SHA
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_REF_PROTECTED
