services:
  db:
    build:
      context: .
      dockerfile: database/Postgres.Dockerfile
    ports:
      - "5432:5432"

  db-change-management:
    build:
      context: .
      dockerfile: database/Liquibase.Dockerfile
      target: base
    volumes:
      - ./database/changelog:/liquibase/changelog
      - ./database/changelogDocs:/liquibase/changelogDocs

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
      args:
        project: api
    ports:
      - "3333:3333"
      - "9229:9229" # default debug port
    volumes:
      - ./apps/api/src:/studio-lite/apps/api/src
      - backend_vol:/studio-lite/packages
    command:
      - "serve"
      - "api"
      - "--host=${API_HOST}"

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
      args:
        project: frontend
        apihost: ${API_HOST}
        apiport: ${API_PORT}
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend/src:/studio-lite/apps/frontend/src
    command:
      - "serve"
      - "frontend"
      - "--host=${WEB_HOST}"

volumes:
  backend_vol:
