services:
  db:
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-db:${TAG}
    restart: always

  liquibase:
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-liquibase:${TAG}

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.rule=(HostRegexp(`www.${SERVER_NAME}`) || Host(`${SERVER_NAME}`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=security-headers"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.services.backend.loadbalancer.server.port=3333"
      - "traefik.docker.network=app-net"
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-backend:${TAG}
    volumes:
      - backend_vol:/studio-lite-api/packages
      - backend_profiles_vol:/studio-lite-api/profiles
    restart: always

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.rule=HostRegexp(`www.${SERVER_NAME}`) || Host(`${SERVER_NAME}`)"
      - "traefik.http.routers.frontend.middlewares=security-headers"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=app-net"
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-frontend:${TAG}
    volumes:
      - ./config/frontend/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    restart: always
