services:
  db:
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-db:${TAG}

  backend:
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-backend:${TAG}
    volumes:
      - backend_vol:/studio-lite/resource-packages

  frontend:
    image: ${REGISTRY_PATH}iqbberlin/studio-lite-frontend:${TAG}
    ports:
      - "80:80"

volumes:
  backend_vol:
