x-env-postgres: &env-postgres
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-env-api: &env-api
  API_HOST: ${API_HOST}
  API_PORT: ${API_PORT}

services:
  db:
    container_name: studio-lite-db
    restart: always
    environment:
      <<: *env-postgres
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    container_name: studio-lite-backend
    depends_on:
      - db
    restart: always
    environment:
      <<: *env-api
      <<: *env-postgres
    networks:
      - backend-network

  frontend:
    container_name: studio-lite-frontend
    depends_on:
      - db
      - backend
    restart: always
    environment:
      <<: *env-api
    networks:
      - backend-network
      - frontend-network

volumes:
  db_vol:

networks:
  backend-network:
  frontend-network:
