x-env-postgres: &env-postgres
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  db:
    container_name: studio-lite-db
    restart: always
    environment:
      <<: *env-postgres
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - db_vol:/data/postgres
    networks:
      - backend-network

volumes:
  db_vol:

networks:
  backend-network:
