services:
  db:
    build:
      context: .
      dockerfile: database/Postgres.Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"

  liquibase:
    build:
      context: .
      dockerfile: database/Liquibase.Dockerfile
      target: base
    volumes:
      - ./database/changelog:/liquibase/changelog
      - ./database/changelogDocs:/liquibase/changelogDocs

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
      args:
        project: api
    volumes:
      - ./apps/api/src:/studio-lite/apps/api/src
      - backend_vol:/studio-lite/packages
    command:
      - "serve"
      - "api"
      - "--host=backend"
    ports:
      - "${API_PORT}:3333"
      - "9229:9229" # default debug port

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
      args:
        project: frontend
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ./apps/frontend/src:/studio-lite/apps/frontend/src
    command:
      - "serve"
      - "frontend"
      - "--host=frontend"
      - "--port=80"

volumes:
  backend_vol:
