services:
  db:
    build:
      context: .
      dockerfile: database/Dockerfile
      target: base
    image: iqbberlin/studio-lite-db:latest
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/updates:/studio-lite-db/updates

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
      args:
        project: api
    image: iqbberlin/studio-lite-backend:latest
    ports:
      - "3333:3333"
      - "9229:9229" # debug port
    command:
      - "serve"
      - "api"
      - "--watch"
    volumes:
      - ./apps/api/src:/studio-lite/apps/api/src

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
      args:
        project: frontend
        apihost: ${API_HOST}
        apiport: ${API_PORT}
    image: iqbberlin/studio-lite-frontend:latest
    ports:
      - "4200:4200"
    command:
      - "serve"
      - "frontend"
      - "--host=${WEB_HOST}"
    volumes:
      - ./apps/frontend/src:/studio-lite/apps/frontend/src
