x-env-postgres: &env-postgres
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  db:
    environment:
      <<: *env-postgres
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - application-network

  liquibase:
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *env-postgres
    command: [
      "liquibase",
      "--url=jdbc:postgresql://db:5432/$POSTGRES_DB",
      "--username=$POSTGRES_USER",
      "--password=$POSTGRES_PASSWORD",
      "--classpath=changelog",
      "--changeLogFile=studio-lite.changelog-root.xml",
      "update"
    ]
    networks:
      - application-network

  backend:
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    environment:
      API_HOST: backend
      <<: *env-postgres
    networks:
      - application-network

  frontend:
    depends_on:
      db:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
      backend:
        condition: service_started
    networks:
      - application-network

volumes:
  db_vol:
  backend_vol:

networks:
  application-network:
    name: app-net
    external: true
