services:
  frontend:
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    volumes:
      - ./ssl/default.conf.template.ssl:/etc/nginx/templates/default.conf.template:ro
      - ./ssl/www.iqb-studio.de.crt:/etc/nginx/ssl/www.iqb-studio.de.crt:ro
      - ./ssl/www.iqb-studio.de.key:/etc/nginx/ssl/www.iqb-studio.de.key:ro
