x-env-postgres: &env-postgres
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-env-api: &env-api
  API_HOST: ${API_HOST}
  API_PORT: ${API_PORT}

services:
  db:
    container_name: studio-lite-db
    restart: always
    environment:
      <<: *env-postgres
    volumes:
      - db_vol:/var/lib/postgresql/data
    healthcheck:
      test: "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
      interval: "1s"
      retries: 60
    networks:
      - backend-network

  db-change-management:
    image: liquibase/liquibase:4.15
    container_name: studio-lite-liquibase
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *env-postgres
      DB_USER: ${POSTGRES_DB_USER}
      DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    networks:
      - backend-network
    command: ["liquibase", "--url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB",  "--username=$POSTGRES_USER", "--password=$POSTGRES_PASSWORD", "--classpath=changelog", "--changeLogFile=studio-lite.changelog-root.xml", "update", "-Ddb.user=${POSTGRES_DB_USER}", "-Ddb.password=${POSTGRES_DB_PASSWORD}"]

  backend:
    container_name: studio-lite-backend
    depends_on:
      db:
        condition: service_healthy
      db-change-management:
        condition: service_completed_successfully
    restart: always
    environment:
      <<: *env-api
      <<: *env-postgres
    networks:
      - backend-network

  frontend:
    container_name: studio-lite-frontend
    depends_on:
      db:
        condition: service_healthy
      db-change-management:
        condition: service_completed_successfully
      backend:
        condition: service_started
    restart: always
    environment:
      <<: *env-api
    networks:
      - backend-network
      - frontend-network

volumes:
  db_vol:

networks:
  backend-network:
  frontend-network:
