services:
  frontend:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl/default.conf.template.ssl:/etc/nginx/templates/default.conf.template
      - ./ssl/www.iqb-studio.de.crt:/etc/nginx/ssl/www.iqb-studio.de.crt
      - ./ssl/www.iqb-studio.de.key:/etc/nginx/ssl/www.iqb-studio.de.key
