-- liquibase formatted sql

-- changeset liquibase:1660919051971-1
CREATE TABLE "public"."user"
(
  "id"                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"                   VARCHAR(50)                              NOT NULL,
  "password"               VARCHAR(100)                             NOT NULL,
  "is_admin"               BOOLEAN DEFAULT FALSE,
  "description"            TEXT,
  "last_name"              VARCHAR(100),
  "first_name"             VARCHAR(100),
  "email"                  VARCHAR(100),
  "email_publish_approved" BOOLEAN DEFAULT FALSE,
  CONSTRAINT "user_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-2
CREATE TABLE "public"."workspace_group"
(
  "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"     VARCHAR(50)                              NOT NULL,
  "settings" JSONB,
  CONSTRAINT "workspace_group_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-3
CREATE TABLE "public"."workspace"
(
  "id"       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name"     VARCHAR(50)                              NOT NULL,
  "group_id" INTEGER                                  NOT NULL,
  "settings" JSONB,
  CONSTRAINT "workspace_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-4
CREATE TABLE "public"."unit_definition"
(
  "id"   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "data" TEXT                                     NOT NULL,
  CONSTRAINT "unit_definition_pk" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-5
CREATE TABLE "public"."unit"
(
  "id"                      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workspace_id"            INTEGER                                  NOT NULL,
  "last_changed_scheme"     TIMESTAMP WITH TIME ZONE DEFAULT NOW()   NOT NULL,
  "key"                     VARCHAR(20)                              NOT NULL,
  "name"                    VARCHAR(100),
  "metadata"                JSONB,
  "variables"               JSONB,
  "scheme"                  TEXT,
  "scheme_type"             VARCHAR(50),
  "editor"                  VARCHAR(50),
  "player"                  VARCHAR(50),
  "schemer"                 VARCHAR(50),
  "definition_id"           INTEGER,
  "last_changed_definition" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "group_name"              VARCHAR(50),
  "description"             TEXT,
  "last_changed_metadata"   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT "unit_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-6
CREATE TABLE "public"."verona_module"
(
  "key"           VARCHAR(50) NOT NULL,
  "metadata"      JSONB,
  "file"          BYTEA,
  "file_size"     INTEGER                  DEFAULT 0,
  "file_datetime" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT "verona_module_pkey" PRIMARY KEY ("key")
);

-- changeset liquibase:1660919051971-7
CREATE TABLE "public"."unit_comment"
(
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "body"       TEXT,
  "user_name"  VARCHAR(100),
  "user_id"    INTEGER,
  "parent_id"  INTEGER,
  "unit_id"    INTEGER                                  NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "changed_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT "unit_comment_pk" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-8
CREATE TABLE "public"."review"
(
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "workspace_id" INTEGER                                  NOT NULL,
  "name"         VARCHAR(100)                             NOT NULL,
  "link"         VARCHAR(100)                             NOT NULL,
  "password"     VARCHAR(100),
  "settings"     JSONB,
  CONSTRAINT "review_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-9
CREATE TABLE "public"."resource_package"
(
  "id"         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "elements"   TEXT[],
  "name"       VARCHAR(100),
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT "resource_package_pkey" PRIMARY KEY ("id")
);

-- changeset liquibase:1660919051971-10
CREATE TABLE "public"."review_unit"
(
  "unit_id"   INTEGER NOT NULL,
  "review_id" INTEGER NOT NULL,
  "order"     INTEGER,
  CONSTRAINT "review_unit_pkey" PRIMARY KEY ("unit_id", "review_id")
);

-- changeset liquibase:1660919051971-11
CREATE TABLE "public"."setting"
(
  "key"     VARCHAR(50) NOT NULL,
  "content" TEXT        NOT NULL,
  CONSTRAINT "app_config_pkey" PRIMARY KEY ("key")
);

-- changeset liquibase:1660919051971-12
CREATE TABLE "public"."unit_user"
(
  "unit_id"                      INTEGER NOT NULL,
  "user_id"                      INTEGER NOT NULL,
  "last_seen_comment_changed_at" TIMESTAMP WITH TIME ZONE,
  CONSTRAINT "unit_user_pkey" PRIMARY KEY ("unit_id", "user_id")
);

-- changeset liquibase:1660919051971-13
CREATE TABLE "public"."workspace_group_admin"
(
  "workspace_group_id" INTEGER NOT NULL,
  "user_id"            INTEGER NOT NULL,
  CONSTRAINT "workspace_group_admin_pkey" PRIMARY KEY ("workspace_group_id", "user_id")
);

-- changeset liquibase:1660919051971-14
CREATE TABLE "public"."workspace_user"
(
  "workspace_id" INTEGER NOT NULL,
  "user_id"      INTEGER NOT NULL,
  CONSTRAINT "workspace_user_pkey" PRIMARY KEY ("workspace_id", "user_id")
);

-- changeset liquibase:1660919051971-15
ALTER TABLE "public"."review_unit"
  ADD CONSTRAINT "review_unit_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "public"."review" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-16
ALTER TABLE "public"."review_unit"
  ADD CONSTRAINT "review_unit_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."unit" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-17
ALTER TABLE "public"."review"
  ADD CONSTRAINT "review_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-18
ALTER TABLE "public"."unit_comment"
  ADD CONSTRAINT "unit_comment_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."unit" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-19
ALTER TABLE "public"."unit"
  ADD CONSTRAINT "unit_definition_id_fk" FOREIGN KEY ("definition_id") REFERENCES "public"."unit_definition" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-20
ALTER TABLE "public"."unit_user"
  ADD CONSTRAINT "unit_user_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES "public"."unit" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-21
ALTER TABLE "public"."unit_user"
  ADD CONSTRAINT "unit_user_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-22
ALTER TABLE "public"."unit"
  ADD CONSTRAINT "unit_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-23
ALTER TABLE "public"."workspace_group_admin"
  ADD CONSTRAINT "workspace_group_admin_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-24
ALTER TABLE "public"."workspace_group_admin"
  ADD CONSTRAINT "workspace_group_admin_workspace_group_id_fkey" FOREIGN KEY ("workspace_group_id") REFERENCES "public"."workspace_group" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-25
ALTER TABLE "public"."workspace"
  ADD CONSTRAINT "workspace_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "public"."workspace_group" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-26
ALTER TABLE "public"."workspace_user"
  ADD CONSTRAINT "workspace_user_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset liquibase:1660919051971-27
ALTER TABLE "public"."workspace_user"
  ADD CONSTRAINT "workspace_user_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- changeset svwolter:28
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- changeset svwolter:29
INSERT INTO public.user (name, password, is_admin)
VALUES ('rondo', crypt('veniziano', gen_salt('bf', 11)), 'True');
