import {
  ACTIVE_THRESHOLD_MS,
  PASSIVE_THRESHOLD_MS,
  HEARTBEAT_PING_INTERVAL_MS,
  UI_BAR_REFRESH_INTERVAL_MS,
  ADMIN_USER_LIST_POLL_INTERVAL_MS,
  ACTIVITY_SYNC_THROTTLE_MS,
  USER_ACTIVITY_THROTTLE_MS,
  POST_MESSAGE_ACTIVITY_THROTTLE_MS,
  AUTO_LOGOUT_REDIRECT_DELAY_MS
} from '@studio-lite/shared-code';

// Re-export app timings from one shared source to keep frontend/backend in sync.
export {
  ACTIVE_THRESHOLD_MS,
  PASSIVE_THRESHOLD_MS,
  HEARTBEAT_PING_INTERVAL_MS,
  UI_BAR_REFRESH_INTERVAL_MS,
  ADMIN_USER_LIST_POLL_INTERVAL_MS,
  ACTIVITY_SYNC_THROTTLE_MS,
  USER_ACTIVITY_THROTTLE_MS,
  POST_MESSAGE_ACTIVITY_THROTTLE_MS,
  AUTO_LOGOUT_REDIRECT_DELAY_MS
};
