import {
  JWT_EXPIRES_IN,
  ACTIVE_SESSION_THRESHOLD_SEC,
  ACTIVE_SESSION_THRESHOLD_MS,
  REFRESH_TOKEN_EXPIRES_IN_SEC,
  REFRESH_TOKEN_EXPIRES_IN_MS,
  INACTIVITY_THRESHOLD_SEC,
  INACTIVITY_THRESHOLD_MS,
  assertTimeConfig
} from '@studio-lite/shared-code';

assertTimeConfig();

export {
  JWT_EXPIRES_IN,
  ACTIVE_SESSION_THRESHOLD_SEC,
  ACTIVE_SESSION_THRESHOLD_MS,
  REFRESH_TOKEN_EXPIRES_IN_SEC,
  REFRESH_TOKEN_EXPIRES_IN_MS,
  INACTIVITY_THRESHOLD_SEC,
  INACTIVITY_THRESHOLD_MS
};
