import {
  JWT_EXPIRES_IN,
  ACTIVE_SESSION_THRESHOLD_SEC,
  REFRESH_TOKEN_EXPIRES_IN_SEC,
  INACTIVITY_THRESHOLD_SEC
} from '@studio-lite/shared-code';

export const ACTIVE_SESSION_THRESHOLD_MS = ACTIVE_SESSION_THRESHOLD_SEC * 1000;
export const REFRESH_TOKEN_EXPIRES_IN_MS = REFRESH_TOKEN_EXPIRES_IN_SEC * 1000;
export const INACTIVITY_THRESHOLD_MS = INACTIVITY_THRESHOLD_SEC * 1000;

export {
  JWT_EXPIRES_IN,
  ACTIVE_SESSION_THRESHOLD_SEC,
  REFRESH_TOKEN_EXPIRES_IN_SEC,
  INACTIVITY_THRESHOLD_SEC
};
