const SECOND_MS = 1000;
const MINUTE_MS = 60 * SECOND_MS;

// Core session and UI timing values shared by frontend and backend.
export const ACTIVE_THRESHOLD_MS = 2 * MINUTE_MS;
export const PASSIVE_THRESHOLD_MS = 3 * MINUTE_MS;

export const HEARTBEAT_PING_INTERVAL_MS = 30 * SECOND_MS;
export const UI_BAR_REFRESH_INTERVAL_MS = SECOND_MS;
export const ADMIN_USER_LIST_POLL_INTERVAL_MS = 15 * SECOND_MS;
export const ACTIVITY_SYNC_THROTTLE_MS = 5 * SECOND_MS;
export const USER_ACTIVITY_THROTTLE_MS = SECOND_MS;
export const POST_MESSAGE_ACTIVITY_THROTTLE_MS = SECOND_MS;
export const AUTO_LOGOUT_REDIRECT_DELAY_MS = SECOND_MS;

export const ACTIVE_SESSION_THRESHOLD_SEC = ACTIVE_THRESHOLD_MS / SECOND_MS;
export const ACTIVE_SESSION_THRESHOLD_MS = ACTIVE_SESSION_THRESHOLD_SEC * SECOND_MS;
export const REFRESH_TOKEN_EXPIRES_IN_SEC = PASSIVE_THRESHOLD_MS / SECOND_MS;
export const INACTIVITY_THRESHOLD_SEC = REFRESH_TOKEN_EXPIRES_IN_SEC;
export const REFRESH_TOKEN_EXPIRES_IN_MS = REFRESH_TOKEN_EXPIRES_IN_SEC * SECOND_MS;
export const INACTIVITY_THRESHOLD_MS = INACTIVITY_THRESHOLD_SEC * SECOND_MS;

export const JWT_EXPIRES_IN = '2m';
